<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'
      class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
            <thead>
            <tr>
                <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Item') ?></span></th>
                <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
            </tr>
            </thead>
            <?php if ($this->helper('Genesisoft\MarketplaceExt\Helper\Data')->getConfig('marketplace/general_settings/group_cart_by_seller')): ?>
                <?php $lastSeller = '';?>
                <?php foreach ($block->getItems() as $_item): ?>
                    <?php $seller = $this->helper('Webkul\Marketplace\Helper\Data')->getSellerProductDataByProductId($_item->getProductId())->getFirstItem()->getName(); ?>
                    <?php $sellerPrint[$seller][] = $block->getItemHtml($_item); ?>
                <?php endforeach; ?>
                <?php ksort($sellerPrint); ?>
                <?php foreach ($sellerPrint as $seller => $sellerProducts): ?>
                    <th>
                        <?php echo $seller; ?>
                    </th>
                    <?php foreach ($sellerProducts as $itemHtml): ?>
                        <?php echo $itemHtml; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <?php foreach ($block->getItems() as $_item) :?>
                    <?= $block->getItemHtml($_item) ?>
                <?php endforeach ?>
            <?php endif; ?>
        </table>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue btn btn-default"
               href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear btn btn-primary" id="empty_cart_button">
            <span><?php /* @escapeNotVerified */ echo __('Clear Shopping Cart'); ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
                class="action update btn btn-primary">
            <span><?php /* @escapeNotVerified */ echo __('Update Shopping Cart'); ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
        <button type="submit"
                name="continue_shopping"
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>"
                class="action update btn btn-primary">
            <a href="<?= $block->getBaseUrl(); ?>" class="action update btn btn-primary"
            <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </button>
    </div>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

